### ISSUE TITLE
Fix the events such that they displaying properly in the newsfeed and in eventDetails

### ISSUE THREAD

**Issue by sarahsvedenborg** [j4hr3n/it2901#172]

**Comment by Sibsen1** [comment]
evenDetails: The dropdowns for participants and types were non-functional, as well as other parameters not working. eventDetails and event-list are now both directives.

newsfeed: Did not link to an actual event. This problem as well as some other bugs was was fixed by renaming the previous controller aliases "evC" to something unique.
